### ISSUE TITLE
Příprava pro implementaci LDAP

### ISSUE THREAD

**Issue by ghost** [ZMJGroup/zswi#13]
Prostudování problematiky LDAP, jeho použitív PHP.
Příprava php souboru.

Předpokládaný čas: 2-3 hodiny

**Comment by FreestyleBros** [comment]
Problematika prostudována, vytvořena kostra pro připojení k active directory. Zadavatel rozmýšlí použití single-sign-on k ověření uživatele.
https://github.com/ZMJGroup/zswi/commit/b8263b49cec745fe583535ccb6ece512dd2ecca3
