### ISSUE TITLE
Funkce aplikace - vyhledávání

### ISSUE THREAD

**Issue by ghost** [ZMJGroup/zswi#19]
Naimplementovat funkci pro vyhledávání v databázi. Uživatel do kolonky v GUI může zadat libovolný řetězec. Tento řetězec se bude vyhledávat v db napříč domluvenými sloupci. V tabulce db se zobrazí vyfiltrovaná data.

Doumluvené sloupce: Jméno,Přijmení,SN,IMEI,Zařízeni,Email(nejdůležitější)

**Comment by rizir01** [comment]
Naimplementováno a commitnuto na git hub. Pocet hodin: 3,5
