### ISSUE TITLE
Implementace ověřování uživatelů

### ISSUE THREAD

**Issue by ghost** [ZMJGroup/zswi#26]
Na základě podkladů od zadavatele naimplementovat ověření uživatele. Pomocí LDAP nebo i Single-Sign-On

**Comment by FreestyleBros** [comment]
připravený základ pro přihlašování přes Single-sign-on 
https://github.com/ZMJGroup/zswi/commit/7a3231af721b25a24018dc550f852a1055b8e7a0

strávený čas: 5h

**Comment by FreestyleBros** [comment]
sso s vlastním providerem, atkualizace a zakládaní uživatelů do databáze hotovo
https://github.com/ZMJGroup/zswi/commit/8047c3da45cbb48a2531d574680631db496e9f52
strávený čas: 6h
