### ISSUE TITLE
Návrh a start implementace uživatelské sekce aplikace

### ISSUE THREAD

**Issue by ghost** [ZMJGroup/zswi#4]
Navržení stránky aplikace, která by se měla uživateli zobrazit po úspěšném přihlášení do aplikace. Zároveň tento návrh začít realizovat a naimplementovat.

předpokládaný čas: 5 - 6 hodin

**Comment by FreestyleBros** [comment]
Stránka navržena, po konzultaci se zadavatelem návrh upraven. Stránka rozdělána a připojena do aplikace. Strávený čas 4 hodiny
