### ISSUE TITLE
Pokračování v implementaci user GUI

### ISSUE THREAD

**Issue by ghost** [ZMJGroup/zswi#8]
Pokračování v implementaci návrhu uživatelského rozhraní.

Odhadovaný čas: 5-6 hodin

**Comment by FreestyleBros** [comment]
Rozhraní kompletně napojené na databázi. Pro benefit tablet stačí drobná úprava.
Strávený čas: 7hodin

**Comment by ghost** [comment]
Předělat položku "Dotace" a formátu datumu na DD.MM.YYYY

**Comment by FreestyleBros** [comment]
formát datumu upraven. Aktuální výše dotace se zprovozní až s nastavením v admin gui.

https://github.com/ZMJGroup/zswi/commit/b8263b49cec745fe583535ccb6ece512dd2ecca3

**Comment by FreestyleBros** [comment]
přidána aktuální výše dotace benefitu
https://github.com/ZMJGroup/zswi/commit/bfe0e0eaa2c21b5ac5da135fd4cdf9a055e33eb7
